version: '3'
services:
  node-app:
    build:
      context: .
    environment:
      - DATABASE_URL
    env_file:
      - .env
    ports:
      - 3500:3500
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"



