name: node.JS CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14,16,17,20.6.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.JS ${ matrix.node-version }
        uses: actions/setup-node@v3
        with:
          node-version: ${ matrix.node-version }

      - name: NPM install, build and test
        run: |
          npm install
          npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
